---
kind: pipeline
type: docker
name: default

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml
  - name: hadolint
    depends_on:
      - yamllint
    image: hadolint/hadolint:2.6.0-alpine
    commands:
      - hadolint --ignore DL3006 Dockerfile
  - name: cargo_clippy
    depends_on:
      - yamllint
    image: rust:1.54
    commands:
      - rustup component add clippy
      - cargo clippy
  - name: docker_build
    depends_on:
      - yamllint
    image: plugins/docker:19.03.8
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username: hsmtkk
      password:
        from_secret: dockerhub_token
      repo: hsmtkk/potential-spoon
      squash: true
